### ISSUE TITLE
why use style objects everywhere instead of actual css?

### ISSUE THREAD

**Issue by jonathanong** [istarkov/google-map-react#103]
i thought it was because maps were loaded in an iframe, but that's not true. style objects make everything more difficult to understand

**Comment by istarkov** [comment]
Please give a link to source.

**Comment by jonathanong** [comment]
for using CSS? http://codepen.io/diana_aceves/pen/HjKdx here's an example. don't have a source though

**Comment by istarkov** [comment]
Link to style objects everywhere. About what style are you talking about?

**Comment by jonathanong** [comment]
oh. stuff like this: https://github.com/istarkov/google-map-react#positioning-a-marker https://github.com/istarkov/google-map-react-examples/blob/master/web/flux/components/examples/x_simple_hover/my_great_place_with_hover_styles.js

all your examples use them

**Comment by istarkov** [comment]
I can't get the problem, in real life I know a lot of issues with css classes. 
Why do I need prefer classes over styles in simple examples as there is no need for me in css selectors and other stuff?

For example read or view this talk https://speakerdeck.com/vjeux/react-css-in-js

For open source project like this I prefer to use `style` elements property, because of css naming scopes and other css stuff.

Also for my internal projects I prefer to use `sass` with `css-modules`. But I'm sure a lot people doesn't know `sass` at all, and never used `css-modules`, so it's not a good idea for simple examples to add sass with css-modules. (And i dislike the idea to write something on pure css)

Also before I wrote this https://github.com/istarkov/babel-plugin-webpack-loaders 
There were a lot of issues with server rendering code and tests.

I don't want to speak below about why classes are better than styles etc, IMHO it's not the problem this project solves ;-)

**Comment by jonathanong** [comment]
Oh it's because you prefer it. I thought it was because it was a technical limitation. I would love examples with regular CSS and an example with CSS modules :) I personally use css modules and can't stand inlined CSS objects.

**Comment by istarkov** [comment]
CSS modules has changed my life ;-)
