### ISSUE TITLE
error if falsy component in GoogleMap

### ISSUE THREAD

**Issue by mihaimetal** [istarkov/google-map-react#164]
If I want to conditionally render a marker, for example:
{ !this.props.fetchingMarkerData && this.props.markers.map(...render markers...) }
I get TypeError: Cannot read property 'props' of null

**Comment by istarkov** [comment]
Your expression returns `false`.
Just return `null`, `undefined` or `empty` array

**Comment by mihaimetal** [comment]
Still getting the error.

**Comment by istarkov** [comment]
https://jsbin.com/kofefelake/edit?js,console,output

**Comment by mihaimetal** [comment]
Yes, all except false.

**Comment by mihaimetal** [comment]
Let's say you have groups of markers.
`{null}{null}` doesn't work.

**Comment by istarkov** [comment]
1) Please provide examples
2) I'm not a `google inc` to check all input user can provide. (And be sure even google does not check anything out of the documentation) There is no fool protection here.

This library is written having in mind an optimistic ideas about that users can provide. As it written for me and for my projects, not for anybody else. U can use it or not.
If you have a real problem please write about, otherwise please stop,
