### ISSUE TITLE
rendering issues

### ISSUE THREAD

**Issue by matanhalevy** [istarkov/google-map-react#181]
Hi thanks for a fantastic library,
I'm working on implementing a similar application to your main example. However I've been running into trouble getting the renderMap to work in my application.

The error seems to be coming from PureRenderer component.
Although it works in the examples you provided this snippet of code is giving me troubles:

`render() {
        const {render, ...other} = this.props;
        return render(other);
    }`

When applying this to my application it breaks for me and I'm confused on what the `other` is and how to maybe declare it differently. (apologies if this is simple, i'm still new to React)

This is my renderMap function, i'm only trying to intially load the map and then add more functionality and include the dispatcher.

```
renderMap(){
        return(
            <Connector select={state => ({
                center: state.map.get('mapInfo').get('center'),
                zoom: state.map.get('mapInfo').get('zoom')
                })}
            >
                {<FindWalkersMap {...mapProps} />}
            </Connector>
        )
    }
```

Appreciae any help!

**Comment by istarkov** [comment]
```const {render, ...other} = this.props``` this is called `object rest spread` and this syntax is not in js specification just in a Stage 2 proposal for ECMAScript.
It can be used with babel stage presets https://github.com/istarkov/google-map-clustering-example/blob/master/package.json#L20

Read here about https://github.com/sebmarkbage/ecmascript-rest-spread

Also main example is over outdated these dates, so can be done 10x more simple than it's done in examples.
Marker animations can be done with `react-motion` as in react-clustering example, instead of fixed-table it's better to use react-virtualized, etc....

**Comment by matanhalevy** [comment]
thanks for the quick reply! I'll read into those and try working it out.

Cheers
