### ISSUE TITLE
Prevent event bubbling on child components

### ISSUE THREAD

**Issue by kjeske** [istarkov/google-map-react#185]
Let's say we have a map like:
```
<GoogleMap
  center={center}
  onClick={() => console.log('map click') }
  >
    <div
      className='marker'
      onClick={(e) => { e.stopPropagation(); console.log('child click'); }}
      >
    </div>
</GoogleMap>
```
When I click on my marker I would expect in console output only "child click", but unfortunately the event bubbles and "map click" is also put into the console. Is there any way to prevent such behaviour?

**Comment by istarkov** [comment]
I haven't checked what's wrong with event propagation in google map. 
As I always use internal hover and click algorithm of this library https://github.com/istarkov/google-map-react#internal-hover-algorithm

Example how to split child clicks and map clicks is here
https://jsbin.com/dayibunuqu/edit?js,console,output

And it split events only if `onChildMouseDown={() => {}}` is defined, I have no idea why I did this, looks like was drunk or something similar ;-)

Also I sometimes use another idea in my work - intercepting `onChildMouseEnter-Leave` events, so any click inside this event pair is click on marker and on map otherwise.

Be sure that both solution used internal hover algorithm, so please read about.

**Comment by istarkov** [comment]
`onChildMouseDown={() => {}}` I think it was some issue with `drag` operation.

**Comment by kjeske** [comment]
Wow, thanks for a quick answer. Adding `onChildMouseDown={() => {}}` does the trick. Thank you!

**Comment by istarkov** [comment]
I reopen this, because it's strange to have such property, to split events, I'll try to fix this some time later.

**Comment by istarkov** [comment]
0.15.1 version works as expected without `onChildMouseDown`
https://jsbin.com/fejuzexika/1/edit?js,console,output

**Comment by kjeske** [comment]
Great! That's awesome

**Comment by rhagigi** [comment]
@istarkov This is now causing me an issue where I *want* to be able to click through the marker. Especially because I'm using top and left to position the marker *above* the marker position (so its a pin pointing directly to the lat/long) and now you can't tap anywhere in the hitbox for the child to move the pin by a street or two! I tried setting pointerEvents to none on my marker and on markerHolderClassName but nothing is working  because I think the click events aren't coming through there specifically. All I want is a "effectively" transparent marker, like on the real google maps. I don't care about click events for my children, only on the map, so click events on children shouldn't stop the map from receiving the clicks. Maybe on https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L743 only check that *if* you are also listening for click events from children?

**Comment by rhagigi** [comment]
I was able to solve the above by setting hoverDistance to 0 to prevent the hover event from ever happening on the markers. 

Ideally though, I'd like to allow dragging the marker to work (again, only on the marker itself but not on the surrounding area), but simple clicks to fall through. Not sure if this is doable with this library (maybe onChildClick could return the actual lat/long clicked on from the map as well, and not just the child's lat/long?) or if I need to write my own. I could also send a PR if you have an idea of how I can accomplish this
