### ISSUE TITLE
Démo pages don't works on IE10 and below

### ISSUE THREAD

**Issue by cateland** [istarkov/google-map-react#2]
Demo works on IE11 all OS, bot not on IE10 and bellow.
![image](https://cloud.githubusercontent.com/assets/1081670/8102515/f1e95e18-1020-11e5-91a0-0700acc27746.png)
![image](https://cloud.githubusercontent.com/assets/1081670/8102521/fb377b1c-1020-11e5-9809-0ce19e7b8283.png)

**Comment by istarkov** [comment]
Thank you, this Microsoft IEs zoo makes me mad. I'll check this today.

**Comment by cateland** [comment]
@istarkov it drive us all mad.
If you can point me to the source of your démo pages i could check into to.

**Comment by istarkov** [comment]
Project
https://github.com/istarkov/google-map-react-examples
Examples
https://github.com/istarkov/google-map-react-examples/tree/master/web/flux/components/examples

**Comment by istarkov** [comment]
@cateland  It looks like it is this https://github.com/zloirock/core-js/issues/62 issue, still not fixed

**Comment by istarkov** [comment]
I found the problem, it is a IE 10 css problem.
see example of my css layout at jsbin http://jsbin.com/yocumahojo/1
it works as expected in chrome and ie11 and doesn't work in ie 10 (red line at top instead of 100% height)

**Comment by istarkov** [comment]
There are two ways to fix this bug. (*css only solutions for server rendering work as expected*)   
Instead of current `fluid height sticky footer-header layout` [sass source](https://github.com/istarkov/google-map-react-examples/blob/master/web/sass/layout.sass)   

I can use
* [Flexbox layout](http://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/) , but it will not work in `IE 9`
* Use fixed layout - but i must explicitly set header footer height (*such layout is not reusable*)

In real life answer depends on web site owner - increase development time-cost (*or use dirty solutions*) to support 2% of old IE browsers users, or support only major browsers versions. And the winner is **use dirty solutions**.

But i don't know what to select for `github example projects` - use bad not reusable layout, or use modern flexbox but without ie9 support or there are other way.

**Comment by istarkov** [comment]
IE-10 Fixed. Changed layout to flex layout. Examples now work in IE-10.
IE-9 coming soon.

**Comment by istarkov** [comment]
IE-9 examples now work without css transitions. As IE-9 does not support transitions. 
And i've decided not to write `javascript` animations for `IE-9 only` in `example project` for code simplicity. But it's possible.

@cateland can you confirm that examples now work in IE-9 and IE-10.

**Comment by cateland** [comment]
@istarkov il check this tomorow at work.

**Comment by cateland** [comment]
Layout work fine on IE10/IE9 but it look like the marker transformation don't apply on IE9

![image](https://cloud.githubusercontent.com/assets/1081670/8157448/21c82a4c-1355-11e5-956a-2a79da69fcdf.png)

**Comment by istarkov** [comment]
Yes, on `ie-9` it's default behavior for this examples.
