### ISSUE TITLE
ReactJs Newbie: guide me on how to get current positoin

### ISSUE THREAD

**Issue by noushad-pp** [istarkov/google-map-react#266]
Can anyone help me on how to get the current position of the user , maybe using `navigator.geolocation.getCurrentPosition();` method or any ways ?

**Comment by mattydoincode** [comment]
Hey noushad! The paradigm for React is a little different than you might be used to. So generally instead of arbitrarily reaching into child components and saying "hey, what is your state?" you instead want to track this information with a larger data loop. Lemme explain:

Lets say you want to display the current center lat/lng to the user when they click a button. One way is something like (in pseudo code):

```
onClickFunctionLocatedOnParentComponent() {
   alert(myMapComponent.getCurrentCenterPosition());
}
```

This is generally the wrong way. First and foremost... how do you get access to `myMapComponent`? This would require you to use [refs](https://facebook.github.io/react/docs/refs-and-the-dom.html) and facebook's documentation there has some great explanations for why that should be a rare requirement in normal use. Instead imagine a more "reacty" way to do this... note I'm using the `onChange` callback you can find in the source code [here](https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L72).

```
onClickFunctionLocatedOnParentComponent() {
    alert(this.state.center);
}

onChangeFunctionLocatedOnParentComponent(data) {
    this.setState({
        center: data.center
    });
}

...

<GoogleMap
onChange={onChangeFunctionLocatedOnParentComponent}
>

</GoogleMap>

```

**Comment by noushad-pp** [comment]
Thanks a ton for the valuable information @mattydoincode. Definitely a time-saver.
