### ISSUE TITLE
pass latitude and longitude to GoogleMapReact center from navigator.geolocation.getCurrentPosition

### ISSUE THREAD

**Issue by freecates** [istarkov/google-map-react#458]
Hi,
I'm trying to use navigator.geolocation.getCurrentPosition to get user current location and pass its coordenates to your component GoogleMapReact center property.

Do you have any solution or pattern?

Thanks a lot!

**Comment by dericcain** [comment]
@freecates I am doing something like that at the moment. One pattern you could use is to have a parent component which gets the user's location on `componentWillMount` and once the location is retrieved, you could use `setState` to update the `lat` and `lng` of the state. Then the GoogleMapReact would simply be a child component of that has the `lat` and `lng` props which would be passed by the parent component's state. For instance...

```JavaScript
export default class MapContainer extends Component {
  
  constructor(props) {
    super(props);
    this.state = {
      lat: null,
      lng: null,
    }
  }

  componentWillMount() {
    navigator.geolocation.getCurrentPosition(
      position => {
        this.setState({ lat: position.coords.latitude, lng: position.coords.longitude});
      },
      error => console.log(error)
    );
  }
 
  render() {
    return (
      <div className="map-container">
        <GoogleMapReact defaultZoom={11} center={{ this.state.lat, this.state.lng }}>
        <Marker lat={this.state.lat} lng={this.state.lng} />
      </GoogleMapReact>
      </div>
    )
  }
}
```
This is not tested and very quick and dirty, but you get the point.

**Comment by theHinneh** [comment]
how do I pass the longitude and latitude received from a firebase database to be rendered in the google map with markers.
please I need help.
I want the markers to show when the database is updated with longitudes and latitudes

**Comment by dericcain** [comment]
@theHinneh You would be best served by asking your question on StackOverflow because you actually seem to have more than one question. For instance, it seems like you are wanting these questions answered:
1. How do I query lat and lng from a Firebase database?
2. How do I render a Google Map using lat and lng (presumably using this library)?
3. How do I make sure that my map is reactive and stays in sync with the reactive nature of Firebase's values?

However, if you do have a more specific question related to this particular comment, fire away! If you have a specific question/bug related to this library, you could open a separate issue. Otherwise, as stated above, you would be best served asking for help on StackOverflow.

**Comment by itsmichaeldiego** [comment]
Thanks for your comment @dericcain, I agree!

**Comment by ShirinStar** [comment]
hey! i keep receiving current location- undefined ... i tried a few version - also this solution, and similar ones that were published along the way here.. any idea maybe what the source for the undefined? 😣many thanks!

**Comment by itsmichaeldiego** [comment]
@ShirinStar Impossible without seeing your code, you must know it can be anything, that's why you should provide a live example reproducing your issue.
