### ISSUE TITLE
Markers are not clickable on mobile

### ISSUE THREAD

**Issue by Shariaty** [istarkov/google-map-react#526]
First i thought it may be something wrong with my code , but when i check demos with my mobile phone i saw it has the same problem , markers are not clickable on mobile phone !!? And every things works fine on desktop.

**Comment by pkrupar** [comment]
I'm experiencing the same problem. Marker `onClick` event doesn't fire when on mobile or simulating mobile from dev tools. Desktop is fine.

I'm using: 0.32.0 google-map-react and react 15.4.2, however as @Shariaty mentioned markers don't work in demo examples too.

I think it could be related to the new google map design. I also noticed that after the new design, map hijacks arrow events for navigation. When I click outside the map, arrows still navigate the map and the original key event doesn't bubble. In my use case this blocks using https://github.com/reactjs/react-modal with arrows for navigation. This issue can be seen on the official demo examples as well.

**Comment by michelemazzucco** [comment]
Hi guys, FYI: I've fixed this issue with "locked" gmap version in loader file: https://github.com/michelemazzucco/google-map-react/blob/bc45189b8ea282a17e549cab68f7e8932128069c/src/utils/loaders/google_map_loader.js#L71

**Comment by itsmichaeldiego** [comment]
@michelemazzucco You don't need to "lock" the gmap version, you can do it in the map `bootstrapUrlKeys`:

```
<GoogleMapReact
  bootstrapURLKeys={{
    key: process.env.REACT_APP_MAP_KEY,
    v: '3.30',
  }}
/>
```

You can also use `3.31`

**Comment by pkrupar** [comment]
Awesome! I can confirm that specifying version `3.30` in `bootstrapURLKeys` fixes the problem. Thanks for the workaround, guys!

**Comment by michelemazzucco** [comment]
Thank you so much @itsmichaeldiego :)

**Comment by Shariaty** [comment]
Thanks , locking the version on 3.30 solved the problem @itsmichaeldiego

**Comment by itsmichaeldiego** [comment]
@Shariaty @michelemazzucco @pkrupar Glad it worked guys, there were a few problems due to google maps updating, this issue is also related to that: https://github.com/istarkov/google-map-react/issues/510. 

I will be taking a look to figure out what is the problem, but in the meantime I am glad that you guys can workaround this with specifying the version.

**Comment by itsmichaeldiego** [comment]
@Shariaty @michelemazzucco @pkrupar I am handling this in #530, so by default we don't have to set the version, the problem is described [in #530's description](https://github.com/istarkov/google-map-react/pull/530#issue-174187310)

**Comment by pkrupar** [comment]
@itsmichaeldiego, you're quick! Thanks for the fix. I'm a bit late and the PR is already merged, but I just wanted to let you know that it looks good. I found just a minor stylistic thing, [here on line 77](https://github.com/istarkov/google-map-react/blob/7dfe4a27754c570a125bfc00a681567d7534eca1/src/utils/loaders/google_map_loader.js#L77),
 unnecessary use of backticks instead of single quotes. But I'm being picky here, thanks again!

**Comment by itsmichaeldiego** [comment]
@pkrupar Oh you're right, I was using a variable there and forgot to remove them, weird that eslint did not throw an error. I am taking care of that [here](https://github.com/istarkov/google-map-react/pull/532/files#diff-4ed1519a6d20f85caa4cc6b843258ecbR79)

**Comment by stephenfarrar** [comment]
FYI: Markers should be clickable in 3.32 as of the latest release.
