### ISSUE TITLE
Makers position is not correct and moving when map repeat more that 2 times

### ISSUE THREAD

**Issue by btbensoft** [istarkov/google-map-react#527]
As discussed in the commentary: [#505](https://github.com/istarkov/google-map-react/issues/505#issuecomment-371421838)

When the plan is repeated more than 2 times (i.e use the full screen with zoomMin 1)

![map](https://image.ibb.co/iL3ZTS/map.png)

the markers moves they are not translate well.

probably a problem with this line:  [here ](https://github.com/istarkov/google-map-react/blob/master/src/google_map_markers.js#206-L269)

```
const pt = this.props.geoService.project(
          latLng,
          this.props.projectFromLeftTop
        );
```

i'm trying use your suggestion add this code to the markers componant:

```
position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
```

But is don't work.

Any idea?

**Comment by itsmichaeldiego** [comment]
@btbensoft If you check the [docs about minZoom](https://github.com/istarkov/google-map-react/blob/master/API.md#override-the-default-minimum-zoom), it states:

> _WARNING:_ Setting this option can break markers calculation, causing no homeomorphism between screen coordinates and map.

The reason of this is that we build React components into the map, and we place them in a X / Y position in the DOM, by setting `left` and `top` properties. 

The map view with minZoom < 2, repeat the maps in order to fit them in the screen, that means that instead of having a whole map, we have at least 2 instances and maybe 3 in your case. 

That causes the calculation to fail, because our calculation is based in 1 whole map and not multiple. 

Sadly, this is not something fixable quick, it has been a problem since the beginning of the library, we initially weren't even allowing to change the `minZoom`, but given that many users wanted to set it, we allowed this option, but with the warning that it might break the calculations, which is what is happening now.

There are 3 ways you could go from here, if you really need this feature _asap_:

- Wait until we fix it (it might take some time, as we will have to re-think the way we calculate the component's position)
- Create your own fix (I can help you out with this, no worries)
- Look for another library

**Comment by btbensoft** [comment]
@itsmichaeldiego, I can help you to work on it. When I'll have some free time! But you have to guide me a bit I do not know the code.

All markers logic is [here](https://github.com/istarkov/google-map-react/blob/master/src/google_map_markers.js)?

**Comment by itsmichaeldiego** [comment]
@btbensoft You're right, that is where the logic is placed, and [here](https://github.com/istarkov/google-map-react/blob/master/src/google_map_markers.js#L266) is where calculate the top / left position.

**Comment by stephenfarrar** [comment]
By the way, this sort of problem might (?) go away if you use the projection from the OverlayView as suggested in https://github.com/istarkov/google-map-react/issues/510#issuecomment-370145748

**Comment by itsmichaeldiego** [comment]
@stephenfarrar You guys are free to make the change <3 I am doing as much as I can with my time availability. Would love to be able to do more.

**Comment by itsmichaeldiego** [comment]
@stephenfarrar @btbensoft We're wrapping all the zoom minZoom issues in #544, would love to get help from you guys, we could create a branch and collaborate all together!

**Comment by btbensoft** [comment]
@itsmichaeldiego, @stephenfarrar  ok im in! But like you, i have a lot of work...
I can try to find some time for this feature/issue.

**Comment by itsmichaeldiego** [comment]
I know @btbensoft no worries, we will get this done! Maybe we can create a collaborative branch

**Comment by btbensoft** [comment]
@itsmichaeldiego First at all, why we don't get the makers system from google maps?

Ok for the branch ;)

**Comment by itsmichaeldiego** [comment]
@btbensoft To be honest I did not write this library, I took it under my wing 2 months ago, so there is still a lot to catch up. Also, from the moment this library was written till now there has been many improvements to google maps in general. 

In my brain, we could totally use the markers system for positioning the markers in the map and then find a way to pass a component to the marker, but there might be a reason why @istarkov did not go this way, either because the markers system was not available or there is something that we're not seeing, I will investigate on this.
