### ISSUE TITLE
onChange instead of onBoundsChange

### ISSUE THREAD

**Issue by bradynapier** [istarkov/google-map-react#95]
GoogleMap: onBoundsChange is deprecated, use onChange({center, zoom, bounds, ...other}) instead.

This warning is coming up.  It appears using onChange does work, it just isn't documented.

**Comment by bradennapier** [comment]
Unfortunately onChange does not appear to be closed properly, causing setState errors so it can't be used.

**Comment by bradennapier** [comment]
To make matters worse, when I look at React Dev Tools I noticed it's rendering markers two times per render and unmounting leaves one of the two in place.  Leaving and coming back will continually add more

![image](https://cloud.githubusercontent.com/assets/15365418/12528253/0e713e0a-c144-11e5-9aac-47a127674518.png)

**Comment by bradennapier** [comment]
annnddd... when i try to send it defaultCenter or defaultZoom eveyr single time the map renders it says you can't change the default Zoom or center... i'm supposed to track if it's been initialized and remove those props?  you can't just ignore them?

**Comment by istarkov** [comment]
Looks like you are doing something wrong.
For example about `defaultCenter`, look at this [jsbin](https://jsbin.com/mejuyeqoqi/edit?js,console,output) example. I've set `defaultCenter` and `defaultZoom` there is no such errors.

Please provide all your errors via jsbin, because I have no idea about your code. 
Provide full information how to reproduce your bugs with any needed steps.

Please respect my time.

**Comment by istarkov** [comment]
Also jsbin example in documentation https://jsbin.com/lepadusowo/edit?js,console,output 
has onChange handler without any issues.
