### ISSUE TITLE
Animating markers without resetting zoom/center

### ISSUE THREAD

**Issue by benjeffery** [istarkov/google-map-react#98]
Hi, maybe I'm misunderstanding something, but I have this problem:
I have a render method that looks like this:
```
    <GoogleMap center={center} zoom={zoom} onChange={this.handleOnChange}>
           <Marker lng={animatedLng} lat={animatedLat}/>
    </GoogleMap>
```
This gets re-rendered for animating lat/lng of the marker. The problem is that on each animation frame center and zoom are being set, so if the user drags the map it gets "sprung" back. If a drag is in progress then center and zoom need to be ignored?
Thanks!

**Comment by istarkov** [comment]
Then user drags map, there are `idle` callbacks on which `center` is changed. 
You could see this behavior here http://istarkov.github.io/google-map-react/map/main/, start drag, stop mouse moving, continue drag. This is expected behavior for my work.
So I will change center and zoom on `idle` events when drag.

Also I'm not sure about your code and animation, there are simple example ref on jsbin in documentation, please extend with your issue and give a reference.

**Comment by benjeffery** [comment]
Well my apologies, constructing the minimal case in a JSBin and it works!
https://jsbin.com/jusoqaxevo/edit?js,console,output
Now I have to figure out what I am doing differently in the actual app.
Thanks.

**Comment by shipstar** [comment]
@benjeffery Did you ever resolve this issue? I am trying to debug a similar problem now. Thanks!

**Comment by istarkov** [comment]
IMHO your problem that you lost referential equality on center prop if it does not changed. 

Or does not use control in controllable way https://github.com/istarkov/google-map-react/issues/87#issuecomment-171331940.

**Comment by benjeffery** [comment]
@shipstar setting the "debounced" prop to false fixed this issue for me - it's negation gets passed though as callExtBoundsChange on https://github.com/istarkov/google-map-react/blob/a6e6b37675a59d5baad38af5bddcecf8afcee076/src/google_map.js#L774 where it prevents a call to "onBoundsChange" which meant that my external state and the map state got out of sync.

@istarkov Feel free to close this issue if you want!
